parameters:
  # user  manager
  user_manager.class: UserBundle\Service\UserManager

services:
  # user manager (vendor agnostic)
  user_manager:
    class: '%user_manager.class%'
    # use direct dependency injection for logger
    arguments: ['@logger', '%kernel.root_dir%']
    tags:
      - { name: monolog.logger, channel: mlp_us }
    # use setter dependency injection for other dependencies
    calls:
      - [setDocumentManager, ['@doctrine_mongodb.odm.document_manager']]
